var BusinessObject = new UCML.BusinessUnit();
BusinessObject.BPOName = "P_Tran_Task_GR";
BusinessObject.GloalServiceName = "";
BusinessObject.IsAssemblyToYun = false;
BusinessObject.AgentID = "EMS_New";
BusinessObject.fitWindow =true;
var ShortCutKeyList = [];
var VC_Tran_Task_GR;
var VC_Tran_Task_GRColumns;
var BC_Tran_TaskBase;
var BC_Tran_TaskColumns;
function onInit()
{
    BC_Tran_TaskBase = new UCML.BusinessComponent();
    BC_Tran_TaskBase.BusinessObject = BusinessObject;
    BC_Tran_TaskBase.TableName = "Tran_Task";
    BC_Tran_TaskBase.BCName = "BC_Tran_Task";
    BC_Tran_TaskBase.fIDENTITYKey = false;
    BC_Tran_TaskBase.AllowModifyJION = false;
    BC_Tran_TaskBase.fHaveUCMLKey = true;
    BC_Tran_TaskBase.fHaveUCMLKey = false;
    BC_Tran_TaskBase.PrimaryKey = "Tran_TaskOID";
    BC_Tran_TaskBase.loaded = true;
    BC_Tran_TaskBase.columns = BC_Tran_TaskColumns;
            BC_Tran_TaskBase.BPOName = "P_Tran_Task_GR";
    BC_Tran_TaskBase.ChangeOnlyOwnerBy = false;
    BC_Tran_TaskBase.EnabledEdit=true;
    BC_Tran_TaskBase.EnabledAppend=true;
    BC_Tran_TaskBase.EnabledDelete=true;
    BC_Tran_TaskBase.RecordOwnerType=0;
    BC_Tran_TaskBase.open();
    VC_Tran_Task_GR = new UCML.DataGrid("VC_Tran_Task_GR");
    VC_Tran_Task_GR.BusinessObject = BusinessObject;
    VC_Tran_Task_GR.dataTable = BC_Tran_TaskBase;
    VC_Tran_Task_GR.columns = VC_Tran_Task_GRColumns;
   VC_Tran_Task_GR.enabledEdit=true;
    VC_Tran_Task_GR.haveMenu=true;
    VC_Tran_Task_GR.parentNodeID="";
    VC_Tran_Task_GR.IsJQMPage=false;
    VC_Tran_Task_GR.JQMPageTheme="";
     VC_Tran_Task_GR.haveScroll=true;
    VC_Tran_Task_GR.HiddenID="";
    VC_Tran_Task_GR.fHidden="false";
    VC_Tran_Task_GR.alignHeight="true";
    VC_Tran_Task_GR.alignWidth="false";

VC_Tran_Task_GR.havePage = false;
VC_Tran_Task_GR.rowNumbers = true;


    VC_Tran_Task_GR.open();
}
function InitCustomInput()
{
}
function onRender()
{
window.TabStrip_Level_1 = new UCML.TabPanel({el:$("#TabStrip_Level_1"), alignWidth: false, alignHeight: true });

}
function onBeforeOpen()
{

fn_BeforeVC();
}
function BusinessInit()
{

fn_InitEv();


}

function BeforeSubmit()
{



    return true
}


 function AfterSubmit()
{



}

function CanSubmit()
{
    var result=true
    for ( var i=0;i<this.UseTableList.length;i++)
    {
        result = this.UseTableList[i].Valiate();
        if (result==false) break;
    }


    return result;
}

function BC_Tran_TaskOnFieldChange(e)
{
}

function fn_InitEv() {
 	var obj={};
	obj.Title_Add="新增-【任务下达】";
	obj.VcName="VC_Tran_Task_GR";
	obj.Url_Edit="Module/sln_Tran/Business/P_Tran_Task_ED.html?UserName="+BC_Tran_TaskBase.getPersonName();
	obj.Url_Add="Module/sln_Tran/Business/P_Tran_Task_ED.html";
	P_InitEv(obj);  
	
}
function fn_BeforeVC(){
//动态添加操作列链接按钮
var obj={};
obj.Type="A,B,C,D,Z";
obj.Z=[
{queryFieldName:'',isQuickQuery:false,isDropDownMode:false,caption:'查看',BCRunMode:5,urlFuncName:"fn_Read"},]

obj.Url_Edit="Module/sln_Tran/Business/P_Tran_Task_ED.html";
obj.Url_Read="Module/sln_Tran/Business/P_Tran_Task_ED.html";
obj.VcName="VC_Tran_Task_GR";
obj.Title_Edit="编辑-【任务下达】";
obj.Title_Read="查看-【任务下达】";
P_Init(obj);
VC_Tran_Task_GR.beforeRowrender=function(){}
}
function fn_Read(){
    // var url = UCMLLocalResourcePath+"Module/sln_Tran/Business/P_Tran_Task_Read.html?w=2&BusinessKeyOID=00000000-0000-0000-0000-000000000000";       
 	 var url = UCMLLocalResourcePath+"Module/sln_Tran/Business/P_Tran_Task_Read.html?&BusinessKeyOID="+BC_Tran_TaskBase.getOID()+"&FlowID="+BC_Tran_TaskBase.getFieldValue("FlowID");             
     var w = new UCML.OpenShowWindow({		
	    frameMode: "frame",  //打开窗体的位置
		modal:true,          //是否有遮盖
		maximizable: true,   //是否有最小化按钮
		maximized:false,     //打开时最小化
		collapsible: true,   //是否有缩小按钮	
		closable:true,       //是否有关闭按钮
		scroll: "yes",       //是否有滚动条
		draggable: true,     //是否能被拖动
		resizable: true,    //是否能改变窗体大小
		ratioWidth:93,     //窗口宽度百分比
		ratioHeight:93,    //窗口高度百分比
	    URL: url,		
		title: "任务下达（阅读）"
	});
	w.open();	
           
           
	
  	
	}
function PrepareColumn() 
{
    BC_Tran_TaskColumns = new Array();
    objColumn = new Object();
    objColumn.fieldName = "Tran_TaskOID";
    objColumn.caption = "主键 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = false;
    objColumn.defaultValue = "";
    objColumn.allowModify = false;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_Created";
    objColumn.caption = "创建日期 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_LAST_UPD";
    objColumn.caption = "最后修改日期 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_Deleted";
    objColumn.caption = "记录删除标记 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "Boolean";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "PersonName";
    objColumn.caption = "创建人 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "PostName";
    objColumn.caption = "创建岗位 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Division";
    objColumn.caption = "创建部门 ";
    objColumn.length = 100;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "OrgName";
    objColumn.caption = "创建单位 ";
    objColumn.length = 100;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "TaskName";
    objColumn.caption = "任务标题 ";
    objColumn.length = 200;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Remark";
    objColumn.caption = "任务描述 ";
    objColumn.length = 500;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "standard";
    objColumn.caption = "完成标准 ";
    objColumn.length = 500;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Start";
    objColumn.caption = "计划开始 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Finish";
    objColumn.caption = "计划完成 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Important";
    objColumn.caption = "重要程度 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "Tran_TaskImportant";
    objColumn.isCodeTable = true;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "DutyPerson";
    objColumn.caption = "负责人 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "DutyPersonFK";
    objColumn.caption = "负责人外键 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Participants";
    objColumn.caption = "参与人（多选） ";
    objColumn.length = 100;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ParticipantsFK";
    objColumn.caption = "参与人外键(多选） ";
    objColumn.length = 500;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "CheckPerson";
    objColumn.caption = "审核人 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "CheckPersonFK";
    objColumn.caption = "审核人外键 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "BusinessState";
    objColumn.caption = "状态 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "Tran_TaskState";
    objColumn.isCodeTable = true;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ActualStart";
    objColumn.caption = "实际开始 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ActualFinish";
    objColumn.caption = "实际完成 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "DateTime";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ProjectName";
    objColumn.caption = "所属项目名称 ";
    objColumn.length = 500;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_CreatedBy";
    objColumn.caption = "创建用户 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_UserOID";
    objColumn.lookupDataSet = "UCML_User";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_REPLACEMENT";
    objColumn.caption = "授权用户 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_UserOID";
    objColumn.lookupDataSet = "UCML_User";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_POSTN";
    objColumn.caption = "所属岗位 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_PostOID";
    objColumn.lookupDataSet = "UCML_Post";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_DIVISION";
    objColumn.caption = "所属部门 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_OrganizeOID";
    objColumn.lookupDataSet = "UCML_Organize";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_ORG";
    objColumn.caption = "所属组织 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_OrganizeOID";
    objColumn.lookupDataSet = "UCML_Organize";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "SYS_LAST_UPD_BY";
    objColumn.caption = "最后修改用户 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "UCML_UserOID";
    objColumn.lookupDataSet = "UCML_User";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Pub_Project_FK";
    objColumn.caption = "工程项目 ";
    objColumn.length = 30;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "Pub_ProjectOID";
    objColumn.lookupDataSet = "Pub_Project";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = true;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "BusinessFlow";
    objColumn.caption = "审批状态 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 5;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "StartFlowFlag";
    objColumn.caption = "流程启动标记 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "Boolean";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "InstanceID";
    objColumn.caption = "流程实例句柄 ";
    objColumn.length = 0;
    objColumn.decLength = 0;
    objColumn.fieldType = "UCMLKey";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "FlowID";
    objColumn.caption = "流程编号 ";
    objColumn.length = 100;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Title";
    objColumn.caption = "流程标题 ";
    objColumn.length = 500;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 0;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Operation";
    objColumn.caption = "操作 ";
    objColumn.length = 50;
    objColumn.decLength = 0;
    objColumn.fieldType = "VarChar";
    objColumn.codeTable = "";
    objColumn.isCodeTable = false;
    objColumn.allowNull = true;
    objColumn.defaultValue = "";
    objColumn.allowModify = true;
    objColumn.foreignKeyField = "";
    objColumn.lookupKeyField = "";
    objColumn.lookupDataSet = "";
    objColumn.lookupResultField = "";
    objColumn.isForeignKey = false;
    objColumn.fieldKind = 3;
    objColumn.isMultiValueField = false;
    objColumn.multiValueTable = "";
    objColumn.isFunctionInitValue = false;
    objColumn.initValueFunc = "";
    objColumn.excelColNo = 0;
    objColumn.IsImageBase64Data = false;
    objColumn.QueryRefColumn = "";
    objColumn.dateTimeFormat = "";
    BC_Tran_TaskColumns[BC_Tran_TaskColumns.length] = objColumn;

    VC_Tran_Task_GRColumns = new Array();
    objColumn = new Object();
    objColumn.fieldName = "Operation";
    objColumn.caption = "操作";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 140;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.fixedColumn  = true;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "TaskName";
    objColumn.caption = "任务标题";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 210;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "left";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.fixedColumn  = true;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "DutyPerson";
    objColumn.caption = "负责人";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 105;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.fixedColumn  = true;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Participants";
    objColumn.caption = "参与人";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 175;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "CheckPerson";
    objColumn.caption = "审核人";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 105;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ProjectName";
    objColumn.caption = "所属项目名称";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 210;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "left";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Important";
    objColumn.caption = "重要程度";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 210;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "left";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Start";
    objColumn.caption = "计划开始";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 175;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.DateBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Finish";
    objColumn.caption = "计划完成";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 175;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.DateBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ActualStart";
    objColumn.caption = "实际开始";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 175;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.DateBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "ActualFinish";
    objColumn.caption = "实际完成";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 175;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.DateBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "BusinessState";
    objColumn.caption = "状态";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 105;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "BusinessFlow";
    objColumn.caption = "审批状态";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 105;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "center";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextBox";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "standard";
    objColumn.caption = "完成标准";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 280;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "left";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextArea";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    objColumn = new Object();
    objColumn.fieldName = "Remark";
    objColumn.caption = "任务描述";
    objColumn.display = true;
    objColumn.allowModify = false;
    objColumn.width = 350;
    objColumn.isFixColumnValue = false;
    objColumn.fixColumnValue = "";
    objColumn.isCustomerControl = false;
    objColumn.align = "left";
    objColumn.customerControl = "";
    objColumn.controlID = "";
    objColumn.editContrl = "";
    objColumn.PromptText = "";
    objColumn.EditType = "UCML.TextArea";
    objColumn.mutiValueCol = false;
    objColumn.inputTip = "";
    VC_Tran_Task_GRColumns[VC_Tran_Task_GRColumns.length] = objColumn;

    ResetColumns(VC_Tran_Task_GRColumns, "VC_Tran_Task_GR");
    PrepareExColumn();
}
